### ISSUE TITLE
TECHX-15.1: Get OASIM hofx working in skylab

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/oasim#4]
Demonstrate a working OASIM hofx within the context of skylab

- [x] Make changes needed to SOCA to provide the ocean/bgc fields required by OASIM
- [ ] Make changes to fv3-jedi to provide the atm fields required by OASIM
- [ ] add to cycling marine skylab configuration

### Goals for Q2
The goal for Q2 of AOP23 is to get available VIIRS/MODIS obs cycling within **Skylab**. The O-B stats will likely look bad, for now. This will mean we will likely take the following shortcuts
* no coupling, running purely with SOCA. Atmospheric fields will either be interpolated to MOM6 grid and read in with SOCA, or a realistic constant value can be specified in the SOCA fields metadata file for each of the atmospheric fields (let's start with the latter).
* The observations will be top-of-atmosphere radiance at first. Adding in a method to do the atmospheric correction, or obtaining other obs that already have this correction, will be done later.

### Goals for Q3
* get working with coupled MOM6/FV3 (need coupling in skylab first)
* use proper bottom-of-atmosphere radiance (ideally we can add a method to calculate this, instead of having to get a separate set of obs)

**Comment by symoore90** [comment]
Can you add this under the TECH Transfer project on the roadmap please

**Comment by symoore90** [comment]
Can you extend this epic out to the end of march please @travissluka

**Comment by travissluka** [comment]
@HamidehGMAO can you give a status update on this

**Comment by HamidehGMAO** [comment]
We ran OASIM for 24 hr Modis data and identified we need to add QC for the geovals/bkg data. For the biochemistry bkg we are communicating with Xiao Liu who has left NOAA EMC, to generate the bkg for the golden month. we don't have anything close to 2022, but I'm going to grab one of Xiao's noda run restart files (e.g., 11/01/2020) as an initial condition for 11/01/2021 and then spin up for 3-4 months to get Feb/Mar 2022 (basically w'd skip a year). Without DA, it should run fairly fast.  For the atmospheric bkg, we are planning to use the GEOS bkg's provided by Jerome and then run CRTM to get the atmospheric variables we need for OASIM input.

**Comment by HamidehGMAO** [comment]
One more note: For now we can try running OASIM hofx with MODIS but for PACE we need CRTM group generate and add PACE's coefficients to CRTM, in order to be able to use hteCRTM to generate the required atmospheric variables.

**Comment by travissluka** [comment]
closing, future issues will be handled under https://github.com/JCSDA-internal/aop24/issues/17
